name: Test
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  ginkgo:
    name: ginkgo
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: go install github.com/onsi/ginkgo/v2/ginkgo@latest && ginkgo run -r --cover --race --junit-report test-report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'test-report.xml'
          check_name: 'Ginkgo Test Report (OS: ${{ matrix.os }})'